// <auto-generated />
using System;
using API_Lawyer.Assets.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Lawyer.Migrations
{
    [DbContext(typeof(LawyerContext))]
    partial class LawyerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API_Lawyer.Model.Movimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Ativo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ProcessoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessoId");

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("API_Lawyer.Model.Origem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Ativo")
                        .HasColumnType("int");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Origens");
                });

            modelBuilder.Entity("API_Lawyer.Model.Processo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Ativo")
                        .HasColumnType("int");

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Distribuicao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroProcesso")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Relator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Volume")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Processos");
                });

            modelBuilder.Entity("API_Lawyer.Model.Transicao", b =>
                {
                    b.Property<int?>("OrigemId")
                        .HasColumnType("int");

                    b.Property<int?>("ProcessoId")
                        .HasColumnType("int");

                    b.HasKey("OrigemId", "ProcessoId");

                    b.HasIndex("ProcessoId");

                    b.ToTable("Transicoes");
                });

            modelBuilder.Entity("API_Lawyer.Model.Movimentacao", b =>
                {
                    b.HasOne("API_Lawyer.Model.Processo", "Processo")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ProcessoId");

                    b.Navigation("Processo");
                });

            modelBuilder.Entity("API_Lawyer.Model.Transicao", b =>
                {
                    b.HasOne("API_Lawyer.Model.Origem", "Origem")
                        .WithMany("Transicoes")
                        .HasForeignKey("OrigemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Lawyer.Model.Processo", "Processo")
                        .WithMany("Transicoes")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Origem");

                    b.Navigation("Processo");
                });

            modelBuilder.Entity("API_Lawyer.Model.Origem", b =>
                {
                    b.Navigation("Transicoes");
                });

            modelBuilder.Entity("API_Lawyer.Model.Processo", b =>
                {
                    b.Navigation("Movimentacoes");

                    b.Navigation("Transicoes");
                });
#pragma warning restore 612, 618
        }
    }
}
